# Generated by Django 3.2 on 2021-08-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210809_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile/user.png', upload_to='profile/'),
        ),
    ]
